import { useTranslation } from 'react-i18next';
import MetaTags from '@/components/seo/meta-tags';

export default function TermsOfUsePage() {
  const { t } = useTranslation();

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 py-12 px-4 sm:px-6 lg:px-8">
      <MetaTags 
        title="Terms of Use"
        description="Terms of Use for the Competitiveness Assessment Service. This service is for entertainment purposes only."
        canonical="/terms-of-use"
      />
      
      <div className="max-w-4xl mx-auto">
        <div className="bg-white rounded-lg shadow-xl p-8">
          <h1 className="text-3xl font-bold text-gray-900 mb-8 text-center">
            Terms of Use
          </h1>
          
          <div className="prose prose-lg max-w-none text-gray-700 space-y-6">
            <section>
              <h2 className="text-2xl font-semibold text-gray-800 mb-4">
                1. Service Purpose
              </h2>
              <p>
                This assessment service is provided for entertainment purposes only. 
                The evaluations and ratings generated by this system are not based on 
                any scientific, psychological, or professional assessment methodology.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-gray-800 mb-4">
                2. No Evaluation Basis
              </h2>
              <p>
                The assessments provided by this service have no legitimate evaluation 
                basis or scientific foundation. The results are generated for fun and 
                entertainment purposes and should not be considered as accurate 
                measurements of any personal characteristics or abilities.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-gray-800 mb-4">
                3. User Responsibility
              </h2>
              <p>
                All judgments and decisions based on the assessment results are 
                entirely up to the user. Users should exercise their own discretion 
                when interpreting or acting upon any results provided by this service.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-gray-800 mb-4">
                4. Limitation of Liability
              </h2>
              <p>
                The service provider assumes no responsibility for any consequences, 
                decisions, or actions taken based on the assessment results. Users 
                participate in this service at their own risk and discretion.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-gray-800 mb-4">
                5. Service Availability
              </h2>
              <p>
                This service is provided "as is" without any warranties. The provider 
                reserves the right to modify, suspend, or discontinue the service at 
                any time without prior notice.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-gray-800 mb-4">
                6. Acceptance of Terms
              </h2>
              <p>
                By using this service, you acknowledge that you have read, understood, 
                and agree to be bound by these Terms of Use. If you do not agree with 
                these terms, please do not use this service.
              </p>
            </section>
          </div>

          <div className="mt-8 text-center">
            <button 
              onClick={() => window.history.back()} 
              className="bg-blue-600 hover:bg-blue-700 text-white font-semibold py-2 px-6 rounded-lg transition-colors"
            >
              Back
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
